cs50web/cs50web/urls.py
from . import views
from django.contrib import admin
from django.urls import path,include

# This is the url page for all project

app_name ='cs50'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='home'),
    path('lecture1/',include("lecture1.urls",namespace='lecture1')), # Connect new apps here 
    path('lecture3/',include("lecture3.urls",namespace='lecture3')), 

]

cs50web/lecture1/urls.py
from django.urls import path
from . import views

app_name ='lecture1'
urlpatterns = [
    path("",views.index,name="index"),
    path("hello",views.hello,name="hello"),
    path("headings",views.headings,name="headings"),
    path("lists",views.lists,name="lists"),
    path("image",views.image,name="image"),
    path("link",views.link,name="link"),
    path("table",views.table,name="table"),
    path("form",views.form,name="form"),
    path("style",views.style,name="style"),
    path("size",views.size,name="size"),
    path("font",views.font,name="font"),
    path("descedant",views.descedant,name="descedant"),
    path("attribute",views.attribute,name="attribute"),
    path("hover",views.hover,name="hover"),
    path("responsive",views.responsive,name="responsive"),
    path("flexbox",views.flexbox,name="flexbox"),
    path("grid",views.grid,name="grid"),
    path("bootstrap",views.bootstrap,name="bootstrap"),
    



# Give url 'alper' , give run function 'alper function insice views ' and a name 

]

cs50web/lecture3/urls.py
from django.urls import path
from . import views

app_name = 'lecture3'
urlpatterns = [
    path("",views.index,name="index"),
    path("hello/<str:name>",views.greet,name="greet"),
    # path("alper",views.alper,name="alper"),
    # path("david",views.david,name="david"),
    path("newyear",views.newyear,name="newyear"),
    path("tasks",views.tasks,name="tasks"),
    path("add",views.add,name="add"),
    path("base",views.base,name="base"),
    path("sum",views.sumO,name="sum"),
    path("statistics",views.stats_,name="statistics"),
]

cs50web/lecture3/models.py
from django.db import models

# Create your models here.

cs50web/cs50web/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,'cs50web/index.html')
    

cs50web/lecture1/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    return render(request,'lecture1/index.html')
    
def hello(request):
    return render(request,'lecture1/hello.html')

def headings(request):
    return render (request,'lecture1/headings.html')

def lists(request):
    return render (request,'lecture1/lists.html')

def image(request):
    return render (request,'lecture1/image.html')

def link(request):
    return render (request,'lecture1/link.html')

def table(request):
    return render (request,'lecture1/table.html')

def form(request):
    return render (request,'lecture1/form.html')

def style(request):
    return render (request,'lecture1/style.html')

def size(request):
    return render (request,'lecture1/size.html')

def font(request):
    return render (request,'lecture1/font.html')

def descedant(request):
    return render (request,'lecture1/descedant.html')

def attribute(request):
    return render (request,'lecture1/attribute.html')

def hover(request):
    return render (request,'lecture1/hover.html')

def responsive(request):
    return render (request,'lecture1/responsive.html')

def flexbox(request):
    return render (request,'lecture1/flexbox.html')

def grid(request):
    return render (request,'lecture1/grid.html')

def bootstrap(request):
    return render (request,'lecture1/bootstrap.html')


# -----------------------------------
def alper(request):
    return HttpResponse("Hello Alper!")

cs50web/lecture3/views.py
from cProfile import label
from statistics import StatisticsError, mean, median, mode, stdev, variance, pstdev
from django.urls import reverse
from datetime import datetime
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django import forms
from matplotlib.pyplot import title
from numpy import number


class NewTaskForm(forms.Form):
    task = forms.CharField(label="New Task")

class twoNumberForm(forms.Form):
    number1 = forms.FloatField(label="Enter Number 1")
    number2 = forms.FloatField(label="Enter Number 2",)

class Stats(forms.Form):
    numbers = forms.CharField(
        label='',
        widget = forms.widgets.Textarea(attrs={'cols': '80', 'rows': '3'}))

# Create your views here.

alper = ['alper']

def index(request):
    return render(request, "lecture3/index.html")

def tasks(request):
    if "tasks5" not in request.session:
        request.session["tasks5"] = []
    return render(request, "lecture3/tasks.html" ,{
        "task1": request.session["tasks5"],
        "name" : alper
    }) # "tasks" is the variable html can access

def add(request):
    if request.method == "POST": # Check if the request method is POST
        form = NewTaskForm(request.POST) # Figure it out all the data they submitted save inside form variable
        if form.is_valid(): # Check if the data is right format
            task = form.cleaned_data["task"] # "task" which is inside the class task
            request.session["tasks5"] += [task]
            return HttpResponseRedirect(reverse("lecture3:tasks"))
            
        else: # If not render the same html page with same form data
            return render(request,"lecture3/add.html", {
                "form": form
        })

    return render(request,"lecture3/add.html", { # if the method is not POST return empty form
        "form": NewTaskForm() 
    })

def greet(request,name):
     return render(request, "lecture3/greet.html", {
         "name": name.capitalize()
     }) # giving this template additional information 'name' so I can use name inside the greet.html 

def newyear(request):
    now = datetime.now()
    return render(request,"lecture3/newyear.html", {
        "newyear" : now.month == 1 and now.day == 1
    })

def base(request):
    return render(request,"lecture3/base.html")

# ---

def stats_(request):
    if request.method == "POST":
        form = Stats(request.POST)
        if form.is_valid():
            numbers = form.cleaned_data["numbers"]
            numbersClean = list(map(float,numbers.split()))
            try:
                var = f"{variance(numbersClean):.3f}"
            except StatisticsError as e:
                var = e
            try:
                sd =  f"{stdev(numbersClean):.3f}"
            except StatisticsError as e:
                sd = e

            return render(request,"lecture3/statistics.html",{
                "form" : form,
                "numbers" : numbersClean,
                "n" : len(numbersClean),
                "sum"  : f"{sum(numbersClean):.3f}",
                "mean" : f"{mean(numbersClean):.3f}",
                "median" : f"{ median(numbersClean)}",
                "mode" : f"{mode(numbersClean)}",
                "var" : var,
                "sd" :  sd
            })
        else:
            return render(request,"lecture3/statistics.html",{
                "form" : form
            })
            
    return render(request,"lecture3/statistics.html",{
        "form" : Stats()
    })

def sumO(request):
    if request.method == "POST":
        form = twoNumberForm(request.POST)
        if form.is_valid():
            number1  = form.cleaned_data["number1"]
            number2  = form.cleaned_data["number2"]
            try:
                div = number1 / number2
            except ZeroDivisionError:
                div = "Zero Division!"
            return render(request,"lecture3/sum.html",{
                'form' : form,
                'sum' : number1 + number2,
                'sub' : number1 - number2,
                'mul' : number1 * number2,
                'div' : div
            })
        else:
            return render(request,"lecture3/add.html", {
                "form": form
            })
    return render(request,"lecture3/sum.html",{
        "form": twoNumberForm()
    })
# -----------------------------------

# def alper(request):
#     return HttpResponse('Hello, Brian!333')

# def david(request):
#     return HttpResponse("Hello, David!")

# def greet(request,name):
#     return HttpResponse(f"Hello, {name.capitalize()}!")

cs50web/lecture1/templates/cs50web/index.html
{% extends "lecture3/layout.html" %}
<!DOCTYPE html>
<html lang = "en">
    <head>
        <title>Main!</title>
    </head>

    <body>
        {% block base %}
        <h1 style="text-align: center;">CS50's Web Programming with Python and JavaScript 2020</h1>

        
        <ul>

            <li>
                <a href="{% url 'lecture1:index' %}" style="font-size: xx-large;">Lecture 0 - HTML and CSS </a>
            </li>
            <li>
                <a  style="font-size: xx-large;">Lecture 1 -  </a>
            </li>
            <li>
                <a  style="font-size: xx-large;">Lecture 2 -  </a>
            </li>

            <li>
                <a href="{% url 'lecture3:index' %}" style="font-size: xx-large;">Lecture 3 - Django </a>
            </li>

        </ul>

        {% endblock %}
    </body>

</html>

cs50web/lecture1/templates/lecture1/attribute.html
<!DOCTYPE html>
<html lang="en">
    <head>
    <title>Hello</title>
        <style>
            a{
                color: blue;
            }

            a[href="https://facebook.com"]{
                color:red;
            }

        </style>
    </head>
    <body>
        <ul>
            <li> <a href="https://google.com">Google</a></li>
            <li> <a href="https://facebook.com">Facebook</a></li>
            <li> <a href="https://amazon.com">Amazon</a></li>
        </ul>
    </body>
</html>

cs50web/lecture1/templates/lecture1/bootstrap.html
<!DOCTYPE html>
<html lang="en">
    <head>

        <title>bootstrap</title>

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    </head>
    <body>
        <div class="alert alert-primary" role="alert">
            A simple primary alert—check it out!
          </div>
          <div class="alert alert-secondary" role="alert">
            A simple secondary alert—check it out!
          </div>
          <div class="alert alert-success" role="alert">
            A simple success alert—check it out!
          </div>
          <div class="alert alert-danger" role="alert">
            A simple danger alert—check it out!
          </div>
          <div class="alert alert-warning" role="alert">
            A simple warning alert—check it out!
          </div>
          <div class="alert alert-info" role="alert">
            A simple info alert—check it out!
          </div>
          <div class="alert alert-light" role="alert">
            A simple light alert—check it out!
          </div>
          <div class="alert alert-dark" role="alert">
            A simple dark alert—check it out!
          </div>
        
    </body>
</html>

cs50web/lecture1/templates/lecture1/form.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Form</title>
    </head>
    <body>
        <form action="">
            <input type="text" placeholder="Full Name" name="name">
            <input type="submit" >
        </form>

        <hr>

        <form action="">

            <div>
                <input type="text" placeholder="Name", name=name2>
                <input type="password" placeholder="Password" name="password">
            </div>
            
            <div>
                Favorite color?
                <input type="radio" name="color" value="red"> red
                <input type="radio" name="color" value="green"> green
                <input type="radio" name="color" value="blue"> blue
                <input type="radio" name="color" value="other"> other
                
            </div>

            <div>
                <input list="countries" name="country" placeholder="Country">
                <datalist id="countries">
                    <option value = "Afganistan">
                    <option value = "Albania">
                    <option value = "Algeria">

                    </option>



                </datalist>


            </div>

            
        </form>

    </body>
</html>

cs50web/lecture1/templates/lecture1/grid.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Document</title>
    <style>
        #grid{
            background-color: green;
            display: grid;
            padding: 20px;
            grid-column-gap: 20px;
            grid-row-gap: 10px;
            grid-template-columns: 200px 200px auto;
        }
        .grid-item{
            background-color: white;
            font-size: 20px;
            padding: 20px;
            text-align: center;            
        }
    </style>
    </head>
    <body>
        <div id="grid">
            <div class ="grid-item">1</div>
            <div class ="grid-item">2</div>
            <div class ="grid-item">3</div>
            <div class ="grid-item">4</div>
            <div class ="grid-item">5</div>
            <div class ="grid-item">6</div>
            <div class ="grid-item">7</div>
            <div class ="grid-item">8</div>
            <div class ="grid-item">9</div>
            <div class ="grid-item">10</div>
        </div>        
    </body>
</html>

cs50web/lecture1/templates/lecture1/headings.html
<!DOCTYPE html>
<html lang ="en">
<head>
    <title>Headings</title>
</head>
<body>

    <h1>This is a heading</h1>
    <h2>This is a smaller heading</h2>
    <h6>This is the smallest heading</h6>

    <hr>    
    <h1>This is a heading 1</h1>
    <h2>This is a heading 2</h2>
    <h3>This is a heading 3</h3>
    <h4>This is a heading 4</h4>
    <h5>This is a heading 5</h5>
    <h6>This is a heading 6</h6>

</body>

</html>

cs50web/lecture1/templates/lecture1/hello.html
<!DOCTYPE html>
<html lang ="en">
<head>
    <title>Hello</title>
</head>
<body>
    Hello, World!
    
</body>

</html>

cs50web/lecture1/templates/lecture1/hover.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Hover</title>

    <style>
        button{
            width: 200px;
            height: 50px;
            font-size: 24px;
            background-color: green;
        
        }
        button:hover{
            background-color: orange;
        }
    </style>
</head>
<body>
    <button>Click me</button>
</body>
</html>

cs50web/lecture1/templates/lecture1/image.html
{% load static %}

<!DOCTYPE html>
<html lang ="en">
<head>
    <title>Image</title>
</head>
<body>

    <!-- !!! DOES NOT WORK FIX IT LATER !!!!-->
    <!-- !!! DOES NOT WORK FIX IT LATER !!!!-->
    <!-- !!! DOES NOT WORK FIX IT LATER !!!!-->
    <img src="ez.png" alt="ez" >
    <img src="{% static 'lecture1/images/ez.png' %}" alt="ez" width="300">   
    
</body>

</html>

cs50web/lecture1/templates/lecture1/link.html
<!DOCTYPE html>
<html lang = "en">
    <head>
        <title>Link!</title>
    </head>

    <body>
        <!--
            https://stackoverflow.com/questions/22938101/best-way-of-linking-to-a-page-in-django
            https://www.thesitewizard.com/html-tutorial/open-links-in-new-window-or-tab.shtml
        -->
    
        <a href="https://google.com"> Click Here!</a>
        <hr>
        <a href="https://google.com" target="_blank"> On a new Tab!</a>
        <hr>
        {% comment %}
            In django works like this 
            "{% url 'list' %}" for different page on same site
        {% endcomment %}
        
        <a href="{% url 'lecture1:lists' %}" > To do Lists page!! </a>
        <hr> 
        <a href="{% url 'lecture1:lists' %}" target="_blank"> To do Lists page in a New tab!! </a> 
    
    </body>
</html>

cs50web/lecture1/templates/lecture1/lists.html
<!DOCTYPE html>
<html lang ="en">
<head>
    <title>Lists</title>
</head>
<body>
    An Unordered List:
    <ul>
        <li>One Item</li>
        <li>Another Item</li>   
        <li>Yet Another Item</li>    
    </ul>


    An Ordered List:
    <ol>
        <li>First Item</li>
        <li>Second Item</li>
        <li>Third Item</li> 
    </ol>
</body>

</html>

cs50web/lecture1/templates/lecture1/responsive.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Document</title>
        <style>
            @media (min-width: 600px){
                body{
                    background-color: rgb(207, 95, 207);
                }
            }
            @media (max-width: 599px){
                body{
                    background-color: red;
                }
            }

        </style>
    </head>
    <body>
        <h1>Welcome to my Web Page!</h1>
    </body>
</html>

cs50web/lecture1/templates/lecture1/size.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Size</title>
        <style>
            .div2{
                background-color: orange;
                width: 200px;
                height: 200px;
                padding: 20px;
                margin: 20px;
                display: inline-block;
            }

            .div3{
                background-color: olivedrab;
                width: 200px;
                height: 200px;
                padding: 20px;
                margin: 20px;
            }
        </style>
        <!-- 
            Common Css 
            padding : Inside
            margin  : Outside

        -->
    </head>
    <body>
        <div style="position: fixed; padding: 0;margin: 0; background-color:orangered;">

            <div class="div2">
                    Hello, world!
            </div> 

            <div class="div2">
                Hello again!
            </div>

            <div class="div2">
                Hello again!
            </div>

            <div class="div3">
                Hello again!
            </div>

            <div class="div3">
                Hello again!
            </div>

            <div class="div3">
                Hello again!
            </div>

        </div>
    </body>
</html>

cs50web/lecture1/templates/lecture1/style.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Hello</title>       
        
        
        <style>
           #foo, #bar{
               color: blue;
           }

           .baz{
               color: red;
           }
           
        </style>

        <!--  
        <style>
            h1{
                color:blue;
                text-align: center;
            }
        </style>
        
        -->
        
        <link rel="stylesheet" href="{% static 'lecture1/css/style.css' %}" />

    </head>
    <body>
        <!-- Instead of writing in every h1 just do it once in the head 
        <h1 style="color: blue; text-align: center; ">Welcome to my Web Page!</h1>

        Improvment
        make styles.css to access from all project 

        -->
        <h1>Welcome to my Web Page!</h1>
        <h1> This is a second heading</h1>
        Hello, world!


        <form >
            <div class = "testDiv">
                <input style="height: 50px; width:100px; border-radius: 25px; background-color:#04aa6d; color:white;border:none" type="button" value="Go back!" onclick="history.back()">

            </div>
        </form>

        <hr>
        <hr>

        <!-- difference between them is that “id” is unique in a page and can only apply to at most one element
            while “class” selector can apply to multiple elements. 
        -->

        <h2 id="foo">Heading 1</h2>
        <h2 id="bar">Heading 2</h2>
        <h2 class="baz">Heading 3</h2>
        <h2 class="baz">Heading 4</h2>
        <h2>Heading 5</h2>
        <h1 id="foo">Css Specifity</h1>
        <ol style="font-size: 20px; font-weight: bold;">
            <li>inline</li>
            <li>id</li>
            <li>class</li>
            <li>type</li>
        </ol>
        

    </body>
</html>

cs50web/lecture1/templates/lecture1/table.html
<!DOCTYPE html>
<html lang = "en">
    <head>
        <title>Table!</title>

        <style>
            .customTable{
                border: 1px solid black;
                border-collapse: collapse;
            }

            .customTH{
                border: 1px solid black;
                padding: 5px;
            }

            .customTD{
                border: 1px solid black;
                padding: 5px;
            }

        </style>

    </head>

    <body>
        <table> <!-- Table -->
            <thead > <!-- Heading of table-->
                <tr>
                    <th>Ocean</th> <!-- table headings One column -->
                    <th>Average Depth</th> <!-- Second Column .. -->
                    <th>Maximum Depth</th>
                </tr>
                </thead>
            <tbody> <!-- Table Body -->
                <tr> <!-- Table Row -->
                    <td>Pacific Ocean </td> <!-- Table Data cells -->
                    <td>4,280 m</td>
                    <td>10,911 m</td>
                </tr> 

                <tr>
                    <td>Atlantic Ocean</td>
                    <td>3,646 m</td>
                    <td>8,486 m </td>
                </tr>

            </tbody>
        </table>

        <hr>
        <!-- Custom Table  ----------------------------------------------------------------------->
        <table class="customTable"> <!-- Table -->
            <thead > <!-- Heading of table-->
                <tr>
                    <th class="customTH">Ocean</th> <!-- table headings One column -->
                    <th class="customTH">Average Depth</th> <!-- Second Column .. -->
                    <th class="customTH">Maximum Depth</th>
                </tr>
                </thead>
            <tbody> <!-- Table Body -->
                <tr> <!-- Table Row -->
                    <td class="customTD">Pacific Ocean </td> <!-- Table Data cells -->
                    <td class="customTD">4,280 m</td>
                    <td class="customTD">10,911 m</td>
                </tr> 

                <tr>
                    <td class="customTD">Atlantic Ocean</td>
                    <td class="customTD">3,646 m</td>
                    <td class="customTD">8,486 m </td>
                </tr>

            </tbody>
        </table>

        <hr>

        <table class="customTable"> <!-- Table -->
            <thead > <!-- Heading of table-->
                <tr>
                    <th class="customTH">Ocean</th> <!-- table headings One column -->
                    <th class="customTH">Average Depth</th> <!-- Second Column .. -->
                    <th class="customTH">Maximum Depth</th>
                </tr>
                </thead>
            <tbody> <!-- Table Body -->
                <tr> <!-- Table Row -->
                    <td class="customTD">Pacific Ocean </td> <!-- Table Data cells -->
                    <td class="customTD">4,280 m</td>
                    <td class="customTD">10,911 m</td>
                </tr> 

                <tr>
                    <td class="customTD">Atlantic Ocean</td>
                    <td class="customTD">3,646 m</td>
                    <td class="customTD">8,486 m </td>
                </tr>

            </tbody>
        </table>



    </body>

</html>

cs50web/lecture3/templates/lecture3/add.html
{% extends "lecture3/layout.html" %}

{% block base %}
{% block body %}
    <!--
    <h1>Add Task</h1>
    <form action="{% url 'lecture3:add' %}" method="POST">
        {% csrf_token %}
        <input type="text" name="task" >
        <input style="margin-bottom: 15px;" type="Submit">
    </form>
    -->
    

    <h1 style="text-align: center;"> Add New Task</h1>
    <form action="{% url 'lecture3:add' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input style="margin-bottom: 15px; " class="btn btn-primary" type="Submit" value="Add">
    </form>

    <a href="{% url 'lecture3:tasks' %}" class="btn btn-primary" >View Tasks</a>

{% endblock %}
{% endblock %}

cs50web/lecture3/templates/lecture3/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block base_title %}Hello {% endblock %}</title>

        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="stylesheet" href="{% static 'lecture3/css/style.css' %}">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    
       
    </head>
    
    
    <body class="bg-light">
        <nav class="navbar navbar-expand-lg navbar navbar-light" style="background-color: #e3f2fd;">
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'home' %}"> Home <span class="sr-only"><!--(current) --></span></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'lecture1:index' %}">Lecture 1</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'lecture3:index' %}">Lecture 3</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link disabled" href="#">Disabled</a>
                </li>
              </ul>
            </div>
        </nav>
        
        <div id="content", name="content", class="main">
            <div class = "row justify-content-center">
                <div class ="col-8">
                    <hr class = "mt-0 mb-4">
                    {% block base %}
                    <div> 
                          test 
                    </div>
                     {% endblock %}
        
                </div>
            </div>
        </div>
        
      

        <!-- Option 1: Bootstrap Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

    </body>
</html>

cs50web/lecture3/templates/lecture3/greet.html
{% extends "lecture3/layout.html" %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Greet</title>
    </head>
    <body>
        {% block base %}
        <h1 style="text-align: center;"> Hello/name! </h1>
        <h3>Hello, {{ name }}!!</h3> <!-- '{{ variable }}'  -->        
        {% endblock %}
    </body>
</html>

cs50web/lecture3/templates/lecture3/index.html
{% extends "lecture3/base.html" %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block base_title %}Lecture3 - Home {% endblock %}</title>
</head>
<body >

    {% block base %}
            
    <h1 style="text-align: center;"> Lecture 3 - Django </h1>
    <ul style="font-size: 25px;">
        
        <li > <a class="n-UL" href="{% url 'lecture3:greet' 'kaan' %}"; title="Hello/anyName">Hello</a>  </li>
        <li > <a class="n-UL" href="{% url 'lecture3:newyear' %}"; title="If - Else  , Static Files">New year</a>  </li>
        <li > <a class="n-UL" href="{% url 'lecture3:tasks' %}"; title="">Tasks</a>  </li>
            <ul>
                <li > <a class="n-UL sec-S" href="{% url 'lecture3:add' %}"; title="">Add Task</a>  </li>

            </ul>
        <li > <a class="n-UL" href="{% url 'lecture3:sum' %}"; title="">Sum</a>  </li>
            <ul>
                <li > <a class="n-UL sec-S" href="{% url 'lecture3:statistics' %}"; title="">Statistics</a>  </li>

            </ul>
    </ul>
    
    {% endblock %}
</body>
</html> 

cs50web/lecture3/templates/lecture3/layout.html
{% extends "lecture3/base.html" %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Tasks</title>
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>

cs50web/lecture3/templates/lecture3/statistics.html
    {% extends "lecture3/base.html" %}

    <!DOCTYPE html>
    <html lang="en">
    <head>
        <title>Document</title>
    </head>
    <body>
    
        {% block base %}
        <h1>Numbers</h1>
            <div class = "container"> 
                <div class = "row">
                    <div class="col-sm">
                        <form action="{% url 'lecture3:statistics' %}" method="POST" >
                            <div class ="input-group mb-3">
                                <div class="input-group-prepend">
                                    {% csrf_token %}
                                    {{ form.as_p }}
                                    <input style="margin-bottom: 15px;" class="btn btn-primary btn-lg" type="Submit">
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="col-sm">
                      <p >Enter numbers with a space. Ex: 3 5 5 3 2 1</p>  
                    </div>
                </div>
            </div>
        
            <hr class = "mt-0 mb-4">
            
            <h3> Numbers : {{ numbers }} </h3>
            <h3> n : {{ n }} </h3>
            <h3> Sum : {{ sum }} </h3>
            <h3> Mean : {{ mean }} </h3>
            <h3> Median : {{ median }} </h3>
            <h3> Mode : {{ mode }} </h3>
            <h3> Variance : {{ var }} </h3>
            <h3> Standard Deviation : {{ sd }} </h3>
        {% endblock %}
    
    </body>
    </html>

cs50web/lecture3/templates/lecture3/sum.html
{% extends "lecture3/base.html" %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Document</title>
</head>
<body>

    {% block base %}
    <h1>Numbers</h1>
        <div class = "container"> 
            <div class = "row">
                <div class="col-sm">
                    <form action="{% url 'lecture3:sum' %}" method="POST" >
                        <div style="margin-left: 10px;" class ="input-group mb-3">
                            <div class="input-group-prepend">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <input style="margin-bottom: 15px;" class="btn btn-primary btn-lg" type="Submit">
                            </div>
                        </div>
                    </form>
                </div>
                <!-- 
                <div class="col-sm">
                    one of thwo
                </div>
                -->
            </div>
        </div>

        <hr class = "mt-0 mb-4">
        <h3> Addition : {{ sum }} </h3>
        <h3> Subtraction : {{ sub }} </h3>
        <h3> Multiplication : {{ mul }} </h3>
        <h3> Division : {{ div }} </h3>
    {% endblock %}

</body>
</html>

cs50web/lecture3/templates/lecture3/tasks.html
{% extends "lecture3/layout.html" %}

{% block base %}
{% block body %}
    <h1>Tasks</h1>
    <ul> 
        
            {% for task in task1 %}
                <li>Task: {{ task }}</li>   
            {% empty %}
                <li>No Tasks. {{ name }}</li>   
            {% endfor %}         
        
        
    </ul>
    
    <a href="{% url 'lecture3:add' %}" class="btn btn-primary">Add a New Task</a>
{% endblock %}
{% endblock %}